" Vim syntax file
" Language: TF2 Config Files
" Maintainer: Horse M.D.
" Latest Revision: 1 May 2014

if exists("b:current_syntax")
    finish
endif

" meta
syn keyword tf2Todo contained TODO FIXME XXX NOTE
syn region tf2Comment display oneline start="//" end="$" keepend contains=tf2Todo

" values
syn match tf2Number '\d\+' contained display
syn match tf2Float '\d\+\.\d*' contained display
syn match tf2Float '\.\d\+\>' contained display

" {{{ Bind-ables
" main keyboard
syn match tf2Key "\s[a-zA-Z0-9]\s"
syn keyword tf2Key END PGDOWN PGUP UPARROW DOWNARROW LEFTARROW RIGHTARROW
syn keyword tf2Key NUMLOCK SCROLLOCK INS HOME DEL ESCAPE F1 F2 F3 F4 F5 F6 F7 F8 F9 F10 F11 F12
syn keyword tf2Key = BACKSPACE TAB \ CAPSLOCK ENTER SHIFT / RSHIFT CTRL ` '
syn keyword tf2Key LWIN ALT SPACE RWIN RCTRL , . SEMICOLON -
" numpad
syn keyword tf2Key KP_SLASH KP_MULTIPLY KP_MINUS KP_PLUS KP_ENTER KP_DEL KP_INS
syn keyword tf2Key KP_HOME KP_UPARROW KP_PGUP KP_LEFTARROW KP_5 KP_RIGHTARROW
syn keyword tf2Key KP_END KP_DOWNARROW KP_PGDN
" moose
syn keyword tf2Key MWHEELUP MWHEELUP MOUSE1 MOUSE2 MOUSE3 MOUSE4 MOUSE5
" }}}

" {{{ Commands:
syn keyword tf2Command _autosave _autosavedangerous _bugreporter_restart _cl_classmenuopen _fov
syn keyword tf2Command _resetgamestats _restart __screenshot_internal abuse_report_queue abuse_report_submit
syn keyword tf2Command achievement_debug achievement_notification_test addip adsp_alley_min adsp_courtyard_min
syn keyword tf2Command adsp_debug adsp_door_height adsp_duct_min adsp_hall_min adsp_low_ceiling
syn keyword tf2Command adsp_opencourtyard_min adsp_openspace_min adsp_openstreet_min adsp_openwall_min adsp_room_min
syn keyword tf2Command adsp_street_min adsp_tunnel_min adsp_wall_height ai_auto_contact_solver ai_block_damage
syn keyword tf2Command ai_debug_assault ai_debug_avoidancebounds ai_debug_directnavprobe ai_debug_doors ai_debug_dyninteractions
syn keyword tf2Command ai_debug_efficiency ai_debug_enemies ai_debug_expressions ai_debug_follow ai_debug_loners
syn keyword tf2Command ai_debug_looktargets ai_debug_los ai_debug_nav ai_debug_node_connect ai_debug_ragdoll_magnets
syn keyword tf2Command ai_debug_shoot_positions ai_debug_speech ai_debug_squads ai_debug_think_ticks ai_debugscriptconditions
syn keyword tf2Command ai_default_efficient ai_drawbattlelines ai_drop_hint ai_dump_hints ai_efficiency_override
syn keyword tf2Command ai_enable_fear_behavior ai_expression_frametime ai_expression_optimization ai_fear_player_dist ai_find_lateral_cover
syn keyword tf2Command ai_find_lateral_los ai_follow_use_points ai_follow_use_points_when_moving ai_force_serverside_ragdoll ai_frametime_limit
syn keyword tf2Command ai_inhibit_spawners ai_lead_time ai_LOS_mode ai_moveprobe_debug ai_moveprobe_jump_debug
syn keyword tf2Command ai_moveprobe_usetracelist ai_navigator_generate_spikes ai_navigator_generate_spikes_strength ai_no_local_paths ai_no_node_cache
syn keyword tf2Command ai_no_select_box ai_no_steer ai_no_talk_delay ai_norebuildgraph ai_path_adjust_speed_on_immediate_turns
syn keyword tf2Command ai_path_insert_pause_at_est_end ai_path_insert_pause_at_obstruction ai_post_frame_navigation ai_radial_max_link_dist ai_reaction_delay_alert
syn keyword tf2Command ai_reaction_delay_idle ai_rebalance_thinks ai_report_task_timings_on_limit ai_sequence_debug ai_set_move_height_epsilon
syn keyword tf2Command ai_setupbones_debug ai_shot_bias ai_shot_bias_max ai_shot_bias_min ai_shot_stats
syn keyword tf2Command ai_shot_stats_term ai_show_hull_attacks ai_show_think_tolerance ai_simulate_task_overtime ai_spread_cone_focus_time
syn keyword tf2Command ai_spread_defocused_cone_multiplier ai_spread_pattern_focus_time ai_strong_optimizations ai_strong_optimizations_no_checkstand ai_task_pre_script
syn keyword tf2Command ai_test_moveprobe_ignoresmall ai_think_limit_label ai_use_clipped_paths ai_use_efficiency ai_use_frame_think_limits
syn keyword tf2Command ai_use_think_optimizations ai_use_visibility_cache ai_vehicle_avoidance air_density alias
syn keyword tf2Command +alt1 -alt1 +alt2 -alt2 ammo_max
syn keyword tf2Command anim_3wayblend anim_showmainactivity anim_showstate anim_showstatelog askconnect_accept
syn keyword tf2Command async_allow_held_files async_mode async_resume async_serialize async_simulate_delay
syn keyword tf2Command async_suspend +attack -attack +attack2 -attack2
syn keyword tf2Command audit_save_in_memory autoaim_max_deflect autoaim_max_dist autosave autosavedangerous
syn keyword tf2Command autosavedangerousissafe +back -back banid banip
syn keyword tf2Command bench_end bench_showstatsdialog bench_start bench_upload benchframe
syn keyword tf2Command bind bind_mac binds_per_command BindToggle blink_duration
syn keyword tf2Command bloodspray bot bot_changeclass bot_changeteams bot_com_meleerange
syn keyword tf2Command bot_com_viewrange bot_com_wpnrange bot_command bot_crouch bot_debug
syn keyword tf2Command bot_dontmove bot_drop bot_forceattack bot_forceattack2 bot_forceattack_down
syn keyword tf2Command bot_forcefireweapon bot_hurt bot_jump bot_kick bot_kill
syn keyword tf2Command bot_mimic bot_mimic_inverse bot_mimic_yaw_offset bot_moveto bot_nav_offsetpathinset
syn keyword tf2Command bot_nav_recomputetime bot_nav_simplifypaths bot_nav_turnspeed bot_nav_usefeelers bot_nav_useoffsetpaths
syn keyword tf2Command bot_nav_wpdeceldistance bot_nav_wpdistance bot_randomnames bot_refill bot_saveme
syn keyword tf2Command bot_selectweaponslot bot_teleport bot_whack box +break
syn keyword tf2Command -break breakable_disable_gib_limit breakable_multiplayer buddha budget_averages_window
syn keyword tf2Command budget_background_alpha budget_bargraph_background_alpha budget_bargraph_range_ms budget_history_numsamplesvisible budget_history_range_ms
syn keyword tf2Command budget_panel_bottom_of_history_fraction budget_panel_height budget_panel_width budget_panel_x budget_panel_y
syn keyword tf2Command budget_peaks_window budget_show_averages budget_show_history budget_show_peaks budget_toggle_group
syn keyword tf2Command bug bug_swap bugreporter_includebsp bugreporter_uploadasync buildcubemaps
syn keyword tf2Command building_cubemaps c_maxdistance c_maxpitch c_maxyaw c_mindistance
syn keyword tf2Command c_minpitch c_minyaw c_orthoheight c_orthowidth cache_print
syn keyword tf2Command cache_print_lru cache_print_summary callvote cam_collision cam_command
syn keyword tf2Command cam_idealdelta cam_idealdist cam_idealdistright cam_idealdistup cam_ideallag
syn keyword tf2Command cam_idealpitch cam_idealyaw cam_showangles cam_snapto +camdistance
syn keyword tf2Command -camdistance +camin -camin +cammousemove -cammousemove
syn keyword tf2Command camortho +camout -camout +campitchdown -campitchdown
syn keyword tf2Command +campitchup -campitchup +camyawleft -camyawleft +camyawright
syn keyword tf2Command -camyawright cancelselect cast_hull cast_ray cc_bot_selectweapon
syn keyword tf2Command cc_captiontrace cc_emit cc_findsound cc_flush cc_lang
syn keyword tf2Command cc_linger_time cc_minvisibleitems cc_predisplay_time cc_random cc_sentencecaptionnorepeat
syn keyword tf2Command cc_showblocks cc_smallfontlength cc_subtitles centerview ch_createairboat
syn keyword tf2Command ch_createjeep changeclass changelevel changelevel2 changelevel_next
syn keyword tf2Command changeteam cl_allowdownload cl_allowupload cl_anglespeedkey cl_animationinfo
syn keyword tf2Command cl_ask_blacklist_for_any_server cl_ask_blacklist_max_session_duration cl_ask_blacklist_opt_out cl_ask_favorite_for_any_server cl_ask_favorite_min_session_duration
syn keyword tf2Command cl_ask_favorite_opt_out cl_autoreload cl_autorezoom cl_backspeed cl_blobbyshadows
syn keyword tf2Command cl_bobcycle cl_bobup cl_boss_show_stun cl_burninggibs cl_chatfilter_version
syn keyword tf2Command cl_chatfilters cl_clanid cl_class cl_clearhinthistory cl_clock_correction
syn keyword tf2Command cl_clock_correction_adjustment_max_amount : cl_clock_correction_adjustment_max_offset : cl_clock_correction_adjustment_min_offset : cl_clock_correction_force_server_tick cl_clock_showdebuginfo
syn keyword tf2Command cl_clockdrift_max_ms cl_clockdrift_max_ms_threadmode cl_cloud_settings cl_cmdrate cl_coach_find_coach
syn keyword tf2Command cl_coach_toggle cl_crosshair_blue cl_crosshair_file cl_crosshair_green cl_crosshair_red
syn keyword tf2Command cl_crosshair_scale cl_crosshairalpha cl_crosshaircolor cl_customsounds cl_debug_player_perf
syn keyword tf2Command cl_debugrumble cl_decline_first_notification cl_demoviewoverride cl_detail_multiplier cl_detaildist
syn keyword tf2Command cl_detailfade cl_disablehtmlmotd cl_downloadfilter cl_drawhud cl_drawleaf
syn keyword tf2Command cl_drawmaterial cl_drawmonitors cl_drawshadowtexture cl_dump_particle_stats cl_dynamiccrosshair
syn keyword tf2Command cl_ejectbrass cl_ent_absbox cl_ent_bbox cl_ent_rbox cl_entityreport
syn keyword tf2Command cl_entityreport_sorted cl_extrapolate cl_extrapolate_amount cl_eyeball_boss_debug cl_fastdetailsprites
syn keyword tf2Command cl_fasttempentcollision cl_find_ent cl_find_ent_index cl_flag_return_height cl_flag_return_size
syn keyword tf2Command cl_flipviewmodels cl_flushentitypacket cl_forcepreload cl_forwardspeed cl_fullupdate
syn keyword tf2Command cl_gameserver_create_identity cl_gameserver_list cl_gameserver_reset_identity cl_gunlowerangle cl_gunlowerspeed
syn keyword tf2Command cl_hud_minmode cl_hudhint_sound cl_idealpitchscale cl_ignorepackets cl_interp
syn keyword tf2Command cl_interp_all cl_interp_npcs cl_interp_ratio cl_interpolate cl_jiggle_bone_debug
syn keyword tf2Command cl_jiggle_bone_debug_pitch_constraints cl_jiggle_bone_debug_yaw_constraints cl_jiggle_bone_framerate_cutoff cl_lagcompensation cl_language
syn keyword tf2Command cl_leveloverview cl_leveloverviewmarker cl_localnetworkbackdoor cl_logofile cl_maxrenderable_dist
syn keyword tf2Command cl_mouseenable cl_mouselook cl_muzzleflash_dlight_1st cl_new_impact_effects cl_notifications_max_num_visible
syn keyword tf2Command cl_notifications_move_time cl_notifications_show_ingame cl_obj_fake_alert cl_obj_test_building_damage cl_observercrosshair
syn keyword tf2Command cl_overdraw_test cl_panelanimation cl_particle_batch_mode cl_particle_max_count cl_particle_retire_cost
syn keyword tf2Command cl_particleeffect_aabb_buffer cl_particles_dump_effects cl_particles_show_bbox cl_pclass cl_pdump
syn keyword tf2Command cl_phys_props_enable cl_phys_props_max cl_phys_props_respawndist cl_phys_props_respawnrate cl_phys_timescale
syn keyword tf2Command cl_pitchdown cl_pitchspeed cl_pitchup cl_playback_screenshots cl_playerspraydisable
syn keyword tf2Command cl_precacheinfo cl_pred_optimize cl_pred_track cl_predict cl_predictionlist
syn keyword tf2Command cl_predictweapons cl_ragdoll_collide cl_ragdoll_fade_time cl_ragdoll_forcefade cl_ragdoll_physics_enable
syn keyword tf2Command cl_ragdoll_pronecheck_distance cl_removedecals cl_resend cl_rumblescale cl_savescreenshotstosteam
syn keyword tf2Command cl_scalecrosshair cl_screenshotlocation cl_screenshotname cl_screenshotusertag cl_SetupAllBones
syn keyword tf2Command cl_shadowtextureoverlaysize cl_show_num_particle_systems cl_show_splashes cl_showanimstate cl_showanimstate_log
syn keyword tf2Command cl_showbackpackrarities cl_showbattery cl_ShowBoneSetupEnts cl_showcrit cl_showdemooverlay
syn keyword tf2Command cl_showents cl_showerror cl_showevents cl_showfps cl_showhelp
syn keyword tf2Command cl_showpausedimage cl_showpluginmessages cl_showpos cl_ShowSunVectors cl_showtextmsg
syn keyword tf2Command cl_sidespeed cl_simulate_no_quicktime cl_smooth cl_smoothtime cl_soundemitter_flush
syn keyword tf2Command cl_soundfile cl_soundscape_flush cl_soundscape_printdebuginfo cl_spec_carrieditems cl_spec_mode
syn keyword tf2Command cl_sporeclipdistance cl_steamscreenshots cl_sun_decay_rate cl_team cl_thirdperson
syn keyword tf2Command cl_threaded_bone_setup cl_threaded_client_leaf_system cl_timeout cl_trade cl_trade_steamid
syn keyword tf2Command cl_trading_show_requests_from cl_training_class_unlock_all cl_training_completed_with_classes cl_trigger_first_notification cl_updaterate
syn keyword tf2Command cl_upspeed cl_use_tournament_specgui cl_view cl_voice_filter cl_vote_ui_active_after_voting
syn keyword tf2Command cl_vote_ui_show_notification cl_winddir cl_windspeed cl_wpn_sway_interp cl_wpn_sway_scale
syn keyword tf2Command cl_yawspeed clear clear_debug_overlays clientport closecaption
syn keyword tf2Command cmd collision_shake_amp collision_shake_freq collision_shake_time collision_test
syn keyword tf2Command colorcorrectionui +commandermousemove -commandermousemove commentary commentary_available
syn keyword tf2Command commentary_cvarsnotchanging commentary_finishnode commentary_firstrun commentary_showmodelviewer commentary_testfirstrun
syn keyword tf2Command con_drawnotify con_enable con_filter_enable con_filter_text con_filter_text_out
syn keyword tf2Command con_logfile con_notifytime con_nprint_bgalpha con_nprint_bgborder con_timestamp
syn keyword tf2Command con_trace condump connect connect_lobby contimes
syn keyword tf2Command coop create_flashlight CreateHairball CreatePredictionError creditsdone
syn keyword tf2Command crosshair currency_give cvarlist datacachesize dbg_demofile
syn keyword tf2Command dbg_spew_connected_players_level dbghist_addline dbghist_dump deathmatch debug_materialmodifycontrol
syn keyword tf2Command debug_materialmodifycontrol_client debug_physimpact debug_touchlinks debugsystemui decalfrequency
syn keyword tf2Command default_fov demo_avellimit demo_debug demo_fastforwardfinalspeed demo_fastforwardramptime
syn keyword tf2Command demo_fastforwardstartspeed demo_fov_override demo_gototick demo_interplimit demo_interpolateview
syn keyword tf2Command demo_legacy_rollback demo_pause demo_pauseatservertick demo_quitafterplayback demo_recordcommands
syn keyword tf2Command demo_resume demo_setendtick demo_timescale demo_togglepause demolist
syn keyword tf2Command demos demoui demoui2 +demoui2 -demoui2
syn keyword tf2Command developer devshots_nextmap devshots_screenshot differences disconnect
syn keyword tf2Command disguise disp_dynamic dispcoll_drawplane displaysoundlist dlight_debug
syn keyword tf2Command download_debug drawcross drawline dropitem dsp_automatic
syn keyword tf2Command dsp_db_min dsp_db_mixdrop dsp_dist_max dsp_dist_min dsp_enhance_stereo
syn keyword tf2Command dsp_facingaway dsp_mix_max dsp_mix_min dsp_off dsp_player
syn keyword tf2Command dsp_reload dsp_room dsp_slow_cpu dsp_spatial dsp_speaker
syn keyword tf2Command dsp_vol_2ch dsp_vol_4ch dsp_vol_5ch dsp_volume dsp_water
syn keyword tf2Command dt_ShowPartialChangeEnts dt_UsePartialChangeEnts dti_flush dtwarning dtwatchclass
syn keyword tf2Command dtwatchent dtwatchvar +duck -duck dump_entity_sizes
syn keyword tf2Command dump_globals dump_panels dump_particlemanifest dump_x360_cfg dump_x360_saves
syn keyword tf2Command dumpentityfactories dumpeventqueue dumpgamestringtable dumplongticks dumpsavedir
syn keyword tf2Command dumpstringtables echo econ_never_show_items_in_cart_count econ_show_items_with_tag editdemo
syn keyword tf2Command editor_toggle enable_debug_overlays endmovie english ent_absbox
syn keyword tf2Command ent_attachments ent_autoaim ent_bbox ent_cancelpendingentfires ent_create
syn keyword tf2Command ent_debugkeys ent_dump ent_fire ent_info ent_keyvalue
syn keyword tf2Command ent_messages ent_messages_draw ent_name ent_orient ent_pause
syn keyword tf2Command ent_pivot ent_rbox ent_remove ent_remove_all ent_rotate
syn keyword tf2Command ent_setname ent_show_response_criteria ent_step ent_teleport ent_text
syn keyword tf2Command ent_viewoffset envmap escape exec exit
syn keyword tf2Command explode explodevector fadein fadeout fast_fogvolume
syn keyword tf2Command filesystem_buffer_size find find_ent find_ent_index findflags
syn keyword tf2Command fire_absorbrate fire_dmgbase fire_dmginterval fire_dmgscale fire_extabsorb
syn keyword tf2Command fire_extscale fire_growthrate fire_heatscale fire_incomingheatscale fire_maxabsorb
syn keyword tf2Command firetarget firstperson fish_debug fish_dormant flex_expression
syn keyword tf2Command flex_looktime flex_maxawaytime flex_maxplayertime flex_minawaytime flex_minplayertime
syn keyword tf2Command flex_rules flex_smooth flex_talk flush flush_locked
syn keyword tf2Command fog_color fog_colorskybox fog_enable fog_enable_water_fog fog_enableskybox
syn keyword tf2Command fog_end fog_endskybox fog_maxdensity fog_maxdensityskybox fog_override
syn keyword tf2Command fog_start fog_startskybox fogui force_centerview +forward
syn keyword tf2Command -forward fov fov_desired fps_max free_pass_peek_debug
syn keyword tf2Command fs_monitor_read_from_pack fs_printopenfiles fs_report_sync_opens fs_warning_level fs_warning_mode
syn keyword tf2Command func_break_max_pieces func_break_reduction_factor func_breakdmg_bullet func_breakdmg_club func_breakdmg_explosive
syn keyword tf2Command fx_drawimpactdebris fx_drawimpactdust fx_drawmetalspark g15_dumpplayer g15_reload
syn keyword tf2Command g15_update_msec g_debug_angularsensor g_debug_constraint_sounds g_debug_doors g_debug_npc_vehicle_roles
syn keyword tf2Command g_debug_ragdoll_removal g_debug_ragdoll_visualize g_debug_trackpather g_debug_transitions g_debug_vehiclebase
syn keyword tf2Command g_debug_vehicledriver g_debug_vehicleexit g_debug_vehiclesound g_Language g_ragdoll_fadespeed
syn keyword tf2Command g_ragdoll_important_maxcount g_ragdoll_lvfadespeed g_ragdoll_maxcount gamemenucommand gameui_activate
syn keyword tf2Command gameui_allowescape gameui_allowescapetoshow gameui_hide gameui_hide_dialog gameui_preventescape
syn keyword tf2Command gameui_preventescapetoshow gameui_show_dialog gameui_xbox getpos ghost_spawn
syn keyword tf2Command give givecurrentammo gl_clear gl_clear_randomcolor global_set
syn keyword tf2Command glow_outline_effect_enable glow_outline_width god +graph -graph
syn keyword tf2Command +grenade1 -grenade1 +grenade2 -grenade2 groundlist
syn keyword tf2Command hammer_update_entity hammer_update_safe_entities hap_damagescale_game hap_HasDevice hap_melee_scale
syn keyword tf2Command hap_noclip_avatar_scale hap_ui_vehicles heartbeat help hide_server
syn keyword tf2Command hideconsole hidehud hidepanel hidestatpanel hl2_episodic
syn keyword tf2Command host_flush_threshold host_framerate host_limitlocal host_map host_profile
syn keyword tf2Command host_runofftime host_showcachemiss host_ShowIPCCallCount host_sleep host_speeds
syn keyword tf2Command host_thread_mode host_timer_report host_timer_spin_ms host_timescale host_writeconfig
syn keyword tf2Command hostip hostname hostport hud_achievement_count hud_achievement_count_engineer
syn keyword tf2Command hud_achievement_description hud_achievement_glowtime hud_achievement_tracker hud_autoaim_method hud_autoaim_scale_icon
syn keyword tf2Command hud_autoreloadscript hud_classautokill hud_combattext hud_combattext_healing hud_deathnotice_time
syn keyword tf2Command hud_draw_active_reticle hud_draw_fixed_reticle hud_drawhistory_time hud_escort_interp hud_escort_test_progress
syn keyword tf2Command hud_escort_test_speed hud_fastswitch hud_freezecamhide hud_lowammowarning_maxposadjust hud_lowammowarning_threshold
syn keyword tf2Command hud_magnetism hud_medicautocallers hud_medicautocallersthreshold hud_medichealtargetmarker hud_reloadscheme
syn keyword tf2Command hud_reticle_alpha_speed hud_reticle_maxalpha hud_reticle_minalpha hud_reticle_scale hud_saytext_time
syn keyword tf2Command hud_takesshots hurtme ifm_basecamera_camerastate ifm_steadycam_2ddragconstant ifm_steadycam_2dspringconstant
syn keyword tf2Command ifm_steadycam_armspeed ifm_steadycam_mousefactor ifm_steadycam_mousepower ifm_steadycam_noise ifm_steadycam_rotatedamp
syn keyword tf2Command ifm_steadycam_rotaterate ifm_steadycam_sensitivity ifm_steadycam_zoomdamp ifm_steadycam_zoomspeed impulse
syn keyword tf2Command in_usekeyboardsampletime incrementvar inspect invnext invprev
syn keyword tf2Command ip item_enable_content_streaming item_quality_chance_common item_quality_chance_rare item_quality_chance_unique
syn keyword tf2Command item_show_whitelistable_definitions itemtest itemtest_botcontrols +jlook -jlook
syn keyword tf2Command join_class join_class joy_accel_filter joy_accelmax joy_accelscale
syn keyword tf2Command joy_advanced joy_advaxisr joy_advaxisu joy_advaxisv joy_advaxisx
syn keyword tf2Command joy_advaxisy joy_advaxisz joy_autoaimdampen joy_autoaimdampenrange joy_autosprint
syn keyword tf2Command joy_axisbutton_threshold joy_diagonalpov joy_display_input joy_forwardsensitivity joy_forwardthreshold
syn keyword tf2Command joy_inverty joy_inverty_default joy_lowend joy_lowmap joy_movement_stick
syn keyword tf2Command joy_movement_stick_default joy_name joy_pegged joy_pitchsensitivity joy_pitchsensitivity_default
syn keyword tf2Command joy_pitchthreshold joy_response_look joy_response_move joy_response_move_vehicle joy_sidesensitivity
syn keyword tf2Command joy_sidethreshold joy_vehicle_turn_lowend joy_vehicle_turn_lowmap joy_virtual_peg joy_wingmanwarrior_centerhack
syn keyword tf2Command joy_wingmanwarrior_turnhack joy_xcontroller_cfg_loaded joy_xcontroller_found joy_yawsensitivity joy_yawsensitivity_default
syn keyword tf2Command joy_yawthreshold joyadvancedupdate joystick jpeg jpeg_quality
syn keyword tf2Command +jump -jump kdtree_test key_findbinding key_listboundkeys
syn keyword tf2Command key_updatelayout kick kickall kickid kill
syn keyword tf2Command killserver killvector +klook -klook lastdisguise
syn keyword tf2Command lastinv +left -left light_crosshair lightcache_maxmiss
syn keyword tf2Command lightprobe linefile listdeaths listdemo listid
syn keyword tf2Command listip listissues listmaps listmodels listRecentNPCSpeech
syn keyword tf2Command load load_itempreset loadcommentary loader_dump_table loader_spew_info
syn keyword tf2Command loader_spew_info_ex localplayer_visionflags lod_TransitionDist log log_verbose_enable
syn keyword tf2Command log_verbose_interval logaddress_add logaddress_del logaddress_delall logaddress_list
syn keyword tf2Command +lookdown -lookdown lookspring lookstrafe +lookup
syn keyword tf2Command -lookup lservercfgfile m_customaccel m_customaccel_exponent m_customaccel_max
syn keyword tf2Command m_customaccel_scale m_filter m_forward m_mouseaccel1 m_mouseaccel2
syn keyword tf2Command m_mousespeed m_pitch m_rawinput m_side m_yaw
syn keyword tf2Command map map_background map_commentary map_edit map_noareas
syn keyword tf2Command map_showspawnpoints mapcyclefile maps mat_aaquality mat_accelerate_adjust_exposure_down
syn keyword tf2Command mat_alphacoverage mat_antialias mat_autoexposure_max mat_autoexposure_min mat_bloom_scalefactor_scalar
syn keyword tf2Command mat_bloomamount_rate mat_bloomscale mat_bufferprimitives mat_bumpbasis mat_bumpmap
syn keyword tf2Command mat_camerarendertargetoverlaysize mat_clipz mat_colcorrection_disableentities mat_color_projection mat_colorcorrection
syn keyword tf2Command mat_compressedtextures mat_configcurrent mat_crosshair mat_crosshair_edit mat_crosshair_explorer
syn keyword tf2Command mat_crosshair_printmaterial mat_crosshair_reloadmaterial mat_debug_autoexposure mat_debug_bloom mat_debug_postprocessing_effects
syn keyword tf2Command mat_debug_process_halfscreen mat_debugalttab mat_debugdepth mat_debugdepthmode mat_debugdepthval
syn keyword tf2Command mat_debugdepthvalmax mat_depthbias_decal mat_depthbias_normal mat_depthbias_shadowmap mat_diffuse
syn keyword tf2Command mat_disable_bloom mat_disable_d3d9ex mat_disable_fancy_blending mat_disable_lightwarp mat_disable_ps_patch
syn keyword tf2Command mat_disablehwmorph mat_drawflat mat_drawTexture mat_drawTextureScale mat_drawTitleSafe
syn keyword tf2Command mat_drawwater mat_dump_rts mat_dxlevel mat_dynamic_tonemapping mat_edit
syn keyword tf2Command mat_envmapsize mat_envmaptgasize mat_excludetextures mat_exposure_center_region_x mat_exposure_center_region_x_flashlight
syn keyword tf2Command mat_exposure_center_region_y mat_exposure_center_region_y_flashlight mat_fastclip mat_fastnobump mat_fastspecular
syn keyword tf2Command mat_fillrate mat_filterlightmaps mat_filtertextures mat_force_bloom mat_force_ps_patch
syn keyword tf2Command mat_force_tonemap_scale mat_forceaniso mat_forcedynamic mat_forcehardwaresync mat_forcemanagedtextureintohardware
syn keyword tf2Command mat_frame_sync_enable mat_frame_sync_force_texture mat_framebuffercopyoverlaysize mat_fullbright mat_hdr_enabled
syn keyword tf2Command mat_hdr_level mat_hdr_manual_tonemap_rate mat_hdr_tonemapscale mat_hdr_uncapexposure mat_hsv
syn keyword tf2Command mat_info mat_leafvis mat_levelflush mat_lightmap_pfms mat_loadtextures
syn keyword tf2Command mat_luxels mat_managedtextures mat_max_worldmesh_vertices mat_maxframelatency mat_measurefillrate
syn keyword tf2Command mat_mipmaptextures mat_monitorgamma mat_monitorgamma_tv_enabled mat_monitorgamma_tv_exp mat_monitorgamma_tv_range_max
syn keyword tf2Command mat_monitorgamma_tv_range_min mat_morphstats mat_motion_blur_enabled mat_motion_blur_falling_intensity mat_motion_blur_falling_max
syn keyword tf2Command mat_motion_blur_falling_min mat_motion_blur_forward_enabled mat_motion_blur_percent_of_screen_max mat_motion_blur_rotation_intensity mat_motion_blur_strength
syn keyword tf2Command mat_non_hdr_bloom_scalefactor mat_norendering mat_normalmaps mat_normals mat_parallaxmap
syn keyword tf2Command mat_picmip mat_postprocess_x mat_postprocess_y mat_postprocessing_combine mat_powersavingsmode
syn keyword tf2Command mat_proxy mat_queue_mode mat_reducefillrate mat_reduceparticles mat_reloadallmaterials
syn keyword tf2Command mat_reloadmaterial mat_reloadtextures mat_remoteshadercompile mat_report_queue_status mat_reporthwmorphmemory
syn keyword tf2Command mat_reversedepth mat_savechanges mat_setvideomode mat_shadowstate mat_show_ab_hdr
syn keyword tf2Command mat_show_ab_hdr_hudelement mat_show_histogram mat_show_texture_memory_usage mat_showcamerarendertarget mat_showenvmapmask
syn keyword tf2Command mat_showframebuffertexture mat_showlightmappage mat_showlowresimage mat_showmaterials mat_showmaterialsverbose
syn keyword tf2Command mat_showmiplevels mat_showtextures mat_showwatertextures mat_slopescaledepthbias_decal mat_slopescaledepthbias_normal
syn keyword tf2Command mat_slopescaledepthbias_shadowmap mat_software_aa_blur_one_pixel_lines mat_software_aa_debug mat_software_aa_edge_threshold mat_software_aa_quality
syn keyword tf2Command mat_software_aa_strength mat_software_aa_strength_vgui mat_software_aa_tap_offset mat_softwarelighting mat_softwareskin
syn keyword tf2Command mat_specular mat_spewvertexandpixelshaders mat_stub mat_supportflashlight mat_supports_d3d9ex
syn keyword tf2Command mat_surfaceid mat_surfacemat mat_texture_limit mat_texture_list +mat_texture_list
syn keyword tf2Command -mat_texture_list mat_texture_list_all mat_texture_list_content_path mat_texture_list_txlod mat_texture_list_txlod_sync
syn keyword tf2Command mat_texture_list_view mat_tonemap_algorithm mat_tonemap_min_avglum mat_tonemap_percent_bright_pixels mat_tonemap_percent_target
syn keyword tf2Command mat_tonemapping_occlusion_use_stencil mat_trilinear mat_use_compressed_hdr_textures mat_viewportscale mat_visualize_dof
syn keyword tf2Command mat_vsync mat_wateroverlaysize mat_wireframe mat_yuv matchmakingport
syn keyword tf2Command maxplayers mem_compact mem_dump mem_dumpstats mem_dumpvballocs
syn keyword tf2Command mem_eat mem_force_flush mem_max_heapsize mem_max_heapsize_dedicated mem_min_heapsize
syn keyword tf2Command mem_periodicdumps mem_test mem_test_each_frame mem_test_every_n_seconds mem_vcollide
syn keyword tf2Command memory memory_diff memory_list memory_mark memory_status
syn keyword tf2Command menuselect meta metamod_version minisave mission_list
syn keyword tf2Command mission_show mm_add_item mm_add_player mm_basedir mm_max_spectators
syn keyword tf2Command mm_message mm_minplayers mm_pluginsfile mm_select_session mm_session_info
syn keyword tf2Command mm_stats mod_dynamicloadpause mod_dynamicloadspew mod_dynamicloadthrottle mod_dynamicmodeldebug
syn keyword tf2Command mod_dynamicunloadtex mod_dynamicunloadtime mod_forcedata mod_forcetouchdata mod_load_anims_async
syn keyword tf2Command mod_load_fakestall mod_load_mesh_async mod_load_showstall mod_load_vcollide_async mod_lock_mdls_on_load
syn keyword tf2Command mod_test_mesh_not_available mod_test_not_available mod_test_verts_not_available mod_touchalldata mod_trace_load
syn keyword tf2Command model_list motd motdfile motdfile_text +movedown
syn keyword tf2Command -movedown +moveleft -moveleft +moveright -moveright
syn keyword tf2Command +moveup -moveup movie_fixwave mp_allowNPCs mp_allowspectators
syn keyword tf2Command mp_autocrosshair mp_autoteambalance mp_blockstyle mp_bonusroundtime mp_capdeteriorate_time
syn keyword tf2Command mp_capstyle mp_chattime mp_clan_ready_signal mp_clan_readyrestart mp_decals
syn keyword tf2Command mp_defaultteam mp_disable_autokick mp_disable_respawn_times mp_enableroundwaittime mp_facefronttime
syn keyword tf2Command mp_fadetoblack mp_falldamage mp_feetyawrate mp_flashlight mp_footsteps
syn keyword tf2Command mp_forceactivityset mp_forceautoteam mp_forcecamera mp_forcerespawn mp_forcerespawnplayers
syn keyword tf2Command mp_forcewin mp_fraglimit mp_friendlyfire mp_highlander mp_holiday_nogifts
syn keyword tf2Command mp_humans_must_join_team mp_idledealmethod mp_idlemaxtime mp_ik mp_match_end_at_timelimit
syn keyword tf2Command mp_maxrounds mp_respawnwavetime mp_restartgame mp_restartgame_immediate mp_restartround
syn keyword tf2Command mp_scrambleteams mp_scrambleteams_auto mp_scrambleteams_auto_windifference mp_show_voice_icons mp_showcleanedupents
syn keyword tf2Command mp_showgestureslots mp_showrespawntimes mp_showroundtransitions mp_simulatemultiplecappers mp_slammoveyaw
syn keyword tf2Command mp_stalemate_enable mp_stalemate_meleeonly mp_stalemate_timelimit mp_switchteams mp_teamlist
syn keyword tf2Command mp_teamoverride mp_teamplay mp_teams_unbalance_limit mp_time_between_capscoring mp_timelimit
syn keyword tf2Command mp_tournament mp_tournament_allow_non_admin_restart mp_tournament_blueteamname mp_tournament_redteamname mp_tournament_restart
syn keyword tf2Command mp_tournament_stopwatch mp_tournament_whitelist mp_usehwmmodels mp_usehwmvcds mp_waitingforplayers_cancel
syn keyword tf2Command mp_waitingforplayers_restart mp_waitingforplayers_time mp_weaponstay mp_windifference mp_windifference_min
syn keyword tf2Command mp_winlimit multvar muzzleflash_light name nav_add_to_selected_set
syn keyword tf2Command nav_add_to_selected_set_by_id nav_analyze nav_analyze_scripted nav_area_bgcolor nav_area_max_size
syn keyword tf2Command nav_avoid nav_begin_area nav_begin_deselecting nav_begin_drag_deselecting nav_begin_drag_selecting
syn keyword tf2Command nav_begin_selecting nav_begin_shift_xy nav_build_ladder nav_check_file_consistency nav_check_floor
syn keyword tf2Command nav_check_stairs nav_chop_selected nav_clear_attribute nav_clear_selected_set nav_clear_walkable_marks
syn keyword tf2Command nav_compress_id nav_connect nav_coplanar_slope_limit nav_coplanar_slope_limit_displacement nav_corner_adjust_adjacent
syn keyword tf2Command nav_corner_lower nav_corner_place_on_ground nav_corner_raise nav_corner_select nav_create_area_at_feet
syn keyword tf2Command nav_create_place_on_ground nav_crouch nav_debug_blocked nav_delete nav_delete_marked
syn keyword tf2Command nav_disconnect nav_disconnect_outgoing_oneways nav_displacement_test nav_dont_hide nav_drag_selection_volume_zmax_offset
syn keyword tf2Command nav_drag_selection_volume_zmin_offset nav_draw_limit nav_dump_selected_set_positions nav_edit nav_end_area
syn keyword tf2Command nav_end_deselecting nav_end_drag_deselecting nav_end_drag_selecting nav_end_selecting nav_end_shift_xy
syn keyword tf2Command nav_flood_select nav_gen_cliffs_approx nav_generate nav_generate_fencetops nav_generate_fixup_jump_areas
syn keyword tf2Command nav_generate_incremental nav_generate_incremental_range nav_generate_incremental_tolerance nav_jump nav_ladder_flip
syn keyword tf2Command nav_load nav_lower_drag_volume_max nav_lower_drag_volume_min nav_make_sniper_spots nav_mark
syn keyword tf2Command nav_mark_attribute nav_mark_unnamed nav_mark_walkable nav_max_view_distance nav_max_vis_delta_list_length
syn keyword tf2Command nav_merge nav_merge_mesh nav_no_hostages nav_no_jump nav_place_floodfill
syn keyword tf2Command nav_place_list nav_place_pick nav_place_replace nav_place_set nav_potentially_visible_dot_tolerance
syn keyword tf2Command nav_precise nav_quicksave nav_raise_drag_volume_max nav_raise_drag_volume_min nav_recall_selected_set
syn keyword tf2Command nav_remove_from_selected_set nav_remove_jump_areas nav_run nav_save nav_save_selected
syn keyword tf2Command nav_select_blocked_areas nav_select_damaging_areas nav_select_half_space nav_select_invalid_areas nav_select_larger_than
syn keyword tf2Command nav_select_obstructed_areas nav_select_orphans nav_select_overlapping nav_select_radius nav_select_stairs
syn keyword tf2Command nav_selected_set_border_color nav_selected_set_color nav_set_place_mode nav_shift nav_show_approach_points
syn keyword tf2Command nav_show_area_info nav_show_compass nav_show_continguous nav_show_danger nav_show_dumped_positions
syn keyword tf2Command nav_show_func_nav_avoid nav_show_func_nav_prefer nav_show_light_intensity nav_show_node_grid nav_show_node_id
syn keyword tf2Command nav_show_nodes nav_show_player_counts nav_show_potentially_visible nav_simplify_selected nav_slope_limit
syn keyword tf2Command nav_slope_tolerance nav_snap_to_grid nav_solid_props nav_splice nav_split
syn keyword tf2Command nav_split_place_on_ground nav_stand nav_stop nav_store_selected_set nav_strip
syn keyword tf2Command nav_subdivide nav_test_node nav_test_node_crouch nav_test_node_crouch_dir nav_test_stairs
syn keyword tf2Command nav_toggle_deselecting nav_toggle_in_selected_set nav_toggle_place_mode nav_toggle_place_painting nav_toggle_selected_set
syn keyword tf2Command nav_toggle_selecting nav_transient nav_unmark nav_update_blocked nav_update_lighting
syn keyword tf2Command nav_update_visibility_on_edit nav_use_place nav_walk nav_warp_to_mark nav_world_center
syn keyword tf2Command nb_allow_avoiding nb_allow_climbing nb_allow_gap_jumping nb_blind nb_command
syn keyword tf2Command nb_debug nb_debug_climbing nb_debug_filter nb_debug_history nb_debug_known_entities
syn keyword tf2Command nb_delete_all nb_force_look_at nb_goal_look_ahead_range nb_head_aim_resettle_angle nb_head_aim_resettle_time
syn keyword tf2Command nb_head_aim_settle_duration nb_head_aim_steady_max_rate nb_ladder_align_range nb_last_area_update_tolerance nb_move_to_cursor
syn keyword tf2Command nb_path_draw_inc nb_path_draw_segment_count nb_path_segment_influence_radius nb_player_crouch nb_player_move
syn keyword tf2Command nb_player_move_direct nb_player_stop nb_player_walk nb_saccade_speed nb_saccade_time
syn keyword tf2Command nb_select nb_shadow_dist nb_speed_look_ahead_range nb_stop nb_update_debug
syn keyword tf2Command nb_update_framelimit nb_update_frequency nb_update_maxslide nb_warp_selected_here net_blockmsg
syn keyword tf2Command net_channels net_chokeloop net_compresspackets net_compresspackets_minsize net_compressvoice
syn keyword tf2Command net_drawslider net_droppackets net_fakejitter net_fakelag net_fakeloss
syn keyword tf2Command net_graph net_graphheight net_graphmsecs net_graphpos net_graphproportionalfont
syn keyword tf2Command net_graphshowinterp net_graphshowlatency net_graphsolid net_graphtext net_maxcleartime
syn keyword tf2Command net_maxfilesize net_maxfragments net_maxpacketdrop net_maxroutable net_queue_trace
syn keyword tf2Command net_queued_packet_thread net_scale net_showdrop net_showevents net_showfragments
syn keyword tf2Command net_showmsg net_showpeaks net_showsplits net_showtcp net_showudp
syn keyword tf2Command net_showudp_wire net_splitpacket_maxrate net_splitrate net_start net_status
syn keyword tf2Command net_udp_rcvbuf net_usesocketsforloopback next nextdemo nextlevel
syn keyword tf2Command nextmap noclip notarget npc_ally_deathmessage npc_height_adjust
syn keyword tf2Command npc_sentences npc_speakall npc_vphysics obj_capture_damage obj_child_damage_factor
syn keyword tf2Command obj_damage_factor obj_dump_damage obj_sapper_amount obj_show_damage object_deterioration_time
syn keyword tf2Command object_verbose old_radiusdamage open_charinfo open_charinfo_armory open_charinfo_backpack
syn keyword tf2Command open_charinfo_crafting open_charinfo_direct open_replaybrowser open_replayinputpanel open_store
syn keyword tf2Command OpenMatchmakingLobby OpenQuickplayDialog OpenSteamWorkshopDialog opentf2options opt_EnumerateLeavesFastAlgorithm
syn keyword tf2Command option_duck_method option_duck_method_default overview_alpha overview_health overview_locked
syn keyword tf2Command overview_mode overview_names overview_tracks overview_zoom particle_sim_alt_cores
syn keyword tf2Command particle_simulateoverflow particle_test_attach_attachment particle_test_attach_mode particle_test_file particle_test_start
syn keyword tf2Command particle_test_stop password path pause perfui
syn keyword tf2Command perfvisualbenchmark perfvisualbenchmark_abort phonemedelay phonemefilter phonemesnap
syn keyword tf2Command phys_impactforcescale phys_penetration_error_time phys_pushscale phys_speeds phys_stressbodyweights
syn keyword tf2Command phys_timescale phys_upimpactforcescale physics_budget physics_constraints physics_debug_entity
syn keyword tf2Command physics_highlight_active physics_report_active physics_select physicsshadowupdate_render picker
syn keyword tf2Command ping pipeline_static_props pixelvis_debug play playdemo
syn keyword tf2Command player_debug_print_damage player_old_armor player_ready_toggle playflush playgamesound
syn keyword tf2Command playsoundscape playvideo playvideo_exitcommand playvol plugin_load
syn keyword tf2Command plugin_pause plugin_pause_all plugin_print plugin_unload plugin_unpause
syn keyword tf2Command plugin_unpause_all +posedebug -posedebug print_colorcorrection progress_enable
syn keyword tf2Command prop_active_gib_limit prop_active_gib_max_fade_time prop_crosshair prop_debug prop_dynamic_create
syn keyword tf2Command prop_physics_create props_break_max_pieces props_break_max_pieces_perframe publish_file_last_dir pwatchent
syn keyword tf2Command pwatchvar pyro_dof pyro_max_intensity pyro_max_rate pyro_max_side_length
syn keyword tf2Command pyro_max_side_width pyro_min_intensity pyro_min_rate pyro_min_side_length pyro_min_side_width
syn keyword tf2Command pyro_vignette pyro_vignette_distortion +quickswitch -quickswitch quit
syn keyword tf2Command r_3dnow r_3dsky r_AirboatViewDampenDamp r_AirboatViewDampenFreq r_AirboatViewZHeight
syn keyword tf2Command r_ambientboost r_ambientfactor r_ambientfraction r_ambientlightingonly r_ambientmin
syn keyword tf2Command r_aspectratio r_avglight r_avglightmap r_bloomtintb r_bloomtintexponent
syn keyword tf2Command r_bloomtintg r_bloomtintr r_cheapwaterend r_cheapwaterstart r_cleardecals
syn keyword tf2Command r_ClipAreaPortals r_colorstaticprops r_debugcheapwater r_debugrandomstaticlighting r_decal_cover_count
syn keyword tf2Command r_decal_cullsize r_decal_overlap_area r_decal_overlap_count r_decals r_decalstaticprops
syn keyword tf2Command r_depthoverlay r_DispBuildable r_DispDrawAxes r_DispWalkable r_dopixelvisibility
syn keyword tf2Command r_drawbatchdecals r_DrawBeams r_drawbrushmodels r_drawclipbrushes r_drawdecals
syn keyword tf2Command r_drawdetailprops r_DrawDisp r_drawentities r_drawflecks r_drawfuncdetail
syn keyword tf2Command r_drawleaf r_drawlightcache r_drawlightinfo r_drawlights r_drawmodeldecals
syn keyword tf2Command r_DrawModelLightOrigin r_drawmodelstatsoverlay r_drawmodelstatsoverlaydistance r_drawmodelstatsoverlaymax r_drawmodelstatsoverlaymin
syn keyword tf2Command r_drawopaquerenderables r_drawopaquestaticpropslast r_drawopaqueworld r_drawothermodels r_drawparticles
syn keyword tf2Command r_drawpixelvisibility r_DrawPortals r_DrawRain r_drawrenderboxes r_drawropes
syn keyword tf2Command r_drawskybox r_DrawSpecificStaticProp r_drawsprites r_drawstaticprops r_drawtranslucentrenderables
syn keyword tf2Command r_drawtranslucentworld r_drawvgui r_drawviewmodel r_drawworld r_dscale_basefov
syn keyword tf2Command r_dscale_fardist r_dscale_farscale r_dscale_neardist r_dscale_nearscale r_dynamic
syn keyword tf2Command r_dynamiclighting r_emulategl r_entity r_entityclips r_eyeglintlodpixels
syn keyword tf2Command r_eyegloss r_eyemove r_eyes r_eyeshift_x r_eyeshift_y
syn keyword tf2Command r_eyeshift_z r_eyesize r_eyewaterepsilon r_farz r_fastzreject
syn keyword tf2Command r_fastzrejectdisp r_flashlight_version2 r_flashlightambient r_flashlightclip r_flashlightconstant
syn keyword tf2Command r_flashlightculldepth r_flashlightdepthres r_flashlightdepthtexture r_flashlightdrawclip r_flashlightdrawdepth
syn keyword tf2Command r_flashlightdrawfrustum r_flashlightdrawfrustumbbox r_flashlightdrawsweptbbox r_flashlightfar r_flashlightfov
syn keyword tf2Command r_flashlightladderdist r_flashlightlinear r_flashlightlockposition r_flashlightmodels r_flashlightnear
syn keyword tf2Command r_flashlightnodraw r_flashlightoffsetx r_flashlightoffsety r_flashlightoffsetz r_flashlightquadratic
syn keyword tf2Command r_flashlightrender r_flashlightrendermodels r_flashlightrenderworld r_flashlightscissor r_flashlightshadowatten
syn keyword tf2Command r_flashlightupdatedepth r_flashlightvisualizetrace r_flex r_flushlod r_ForceWaterLeaf
syn keyword tf2Command r_frustumcullworld r_glint_alwaysdraw r_glint_procedural r_hunkalloclightmaps r_hwmorph
syn keyword tf2Command r_itemblinkmax r_itemblinkrate r_JeepFOV r_JeepViewBlendTo r_JeepViewBlendToScale
syn keyword tf2Command r_JeepViewBlendToTime r_JeepViewDampenDamp r_JeepViewDampenFreq r_JeepViewZHeight r_lightaverage
syn keyword tf2Command r_lightcache_numambientsamples r_lightcache_zbuffercache r_lightcachecenter r_lightcachemodel r_lightinterp
syn keyword tf2Command r_lightmap r_lightstyle r_lightwarpidentity r_lockpvs r_lod
syn keyword tf2Command r_mapextents r_maxdlights r_maxmodeldecal r_maxnewsamples r_maxsampledist
syn keyword tf2Command r_minnewsamples r_modelwireframedecal r_newflashlight r_nohw r_norefresh
syn keyword tf2Command r_nosw r_novis r_occludeemaxarea r_occluderminarea r_occludermincount
syn keyword tf2Command r_occlusion r_occlusionspew r_oldlightselection r_overlayfadeenable r_overlayfademax
syn keyword tf2Command r_overlayfademin r_overlaywireframe r_particle_sim_spike_threshold_ms r_particle_timescale r_partition_level
syn keyword tf2Command r_PhysPropStaticLighting r_pix_recordframes r_pix_start r_pixelfog r_pixelvisibility_partial
syn keyword tf2Command r_pixelvisibility_spew r_portalscloseall r_portalsopenall r_PortalTestEnts r_printdecalinfo
syn keyword tf2Command r_proplightingfromdisk r_proplightingpooling r_propsmaxdist r_queued_decals r_queued_post_processing
syn keyword tf2Command r_queued_ropes r_radiosity r_rainalpha r_rainalphapow r_raindensity
syn keyword tf2Command r_RainHack r_rainlength r_RainProfile r_RainRadius r_RainSideVel
syn keyword tf2Command r_RainSimulate r_rainspeed r_RainSplashPercentage r_rainwidth r_randomflex
syn keyword tf2Command r_renderoverlayfragment r_rimlight r_rootlod r_rope_holiday_light_scale r_ropes_holiday_light_color
syn keyword tf2Command r_ropes_holiday_lights_allowed r_ropetranslucent r_screenfademaxsize r_screenfademinsize r_screenoverlay
syn keyword tf2Command r_sequence_debug r_shader_srgb r_shadowangles r_shadowblobbycutoff r_shadowcolor
syn keyword tf2Command r_shadowdir r_shadowdist r_shadowids r_shadowlod r_shadowlodbias
syn keyword tf2Command r_shadowmaxrendered r_shadowrendertotexture r_shadows r_shadows_gamecontrol r_shadowwireframe
syn keyword tf2Command r_showenvcubemap r_ShowViewerArea r_showz_power r_skin r_skybox
syn keyword tf2Command r_snapportal r_SnowColorBlue r_SnowColorGreen r_SnowColorRed r_SnowDebugBox
syn keyword tf2Command r_SnowEnable r_SnowEndAlpha r_SnowEndSize r_SnowFallSpeed r_SnowInsideRadius
syn keyword tf2Command r_SnowOutsideRadius r_SnowParticles r_SnowPosScale r_SnowRayEnable r_SnowRayLength
syn keyword tf2Command r_SnowRayRadius r_SnowSpeedScale r_SnowStartAlpha r_SnowStartSize r_SnowWindScale
syn keyword tf2Command r_SnowZoomOffset r_SnowZoomRadius r_spewleaf r_spray_lifetime r_sse2
syn keyword tf2Command r_sse_s r_staticprop_lod r_staticpropinfo r_studio_stats r_studio_stats_lock
syn keyword tf2Command r_studio_stats_mode r_swingflashlight r_teeth r_threaded_client_shadow_manager r_threaded_particles
syn keyword tf2Command r_threaded_renderables r_unloadlightmaps r_updaterefracttexture r_vehicleBrakeRate r_VehicleViewClamp
syn keyword tf2Command r_VehicleViewDampen r_visambient r_visocclusion r_visualizelighttraces r_visualizelighttracesshowfulltrace
syn keyword tf2Command r_visualizeproplightcaching r_visualizetraces r_WaterDrawReflection r_WaterDrawRefraction r_waterforceexpensive
syn keyword tf2Command r_waterforcereflectentities r_worldlightmin r_worldlights r_worldlistcache ragdoll_sleepaftertime
syn keyword tf2Command randommap rate rbgc rcon rcon_address
syn keyword tf2Command rcon_password recompute_speed record refresh_options_dialog RefreshMatchmakingLobby
syn keyword tf2Command refreshplayerstats reload +reload -reload reload_materials
syn keyword tf2Command removeid removeip replay_add_fake_replays replay_block_dump_interval replay_buffersize
syn keyword tf2Command replay_cache_client_ragdolls replay_clearqueuedtakes replay_confirmquit replay_data_lifespan replay_deathcammaxverticaloffset
syn keyword tf2Command replay_debug replay_deleteclientreplays replay_docleanup replay_dodiskcleanup replay_dofileserver_cleanup_on_start
syn keyword tf2Command replay_dopublishtest replay_editor_camera_length replay_editor_fov_mousewheel_invert replay_editor_fov_mousewheel_multiplier replay_enable
syn keyword tf2Command replay_enableeventbasedscreenshots replay_enablerenderpreview replay_fileserver_autocleanup replay_fileserver_host replay_fileserver_offload_aborttime
syn keyword tf2Command replay_fileserver_offload_enable replay_fileserver_offload_hostname replay_fileserver_offload_login replay_fileserver_offload_maxuploads replay_fileserver_offload_password
syn keyword tf2Command replay_fileserver_offload_port replay_fileserver_offload_protocol replay_fileserver_offload_proxy_host replay_fileserver_offload_proxy_port replay_fileserver_offload_remotepath
syn keyword tf2Command replay_fileserver_offload_useproxy replay_fileserver_path replay_fileserver_port replay_fileserver_protocol replay_flushinterval
syn keyword tf2Command replay_forcereconstruct replay_hidebrowser replay_ignorereplayticks replay_local_fileserver_path replay_max_publish_threads
syn keyword tf2Command replay_maxconcurrentdownloads replay_maxscreenshotsperreplay replay_mintimebetweenscreenshots replay_movie_export_last_dir replay_movie_reveal_warning
syn keyword tf2Command replay_msgduration_connectrecording replay_msgduration_error replay_msgduration_misc replay_msgduration_replaysavailable replay_msgduration_startrecord
syn keyword tf2Command replay_msgduration_stoprecord replay_name replay_perftip_count_enter replay_perftip_count_exit replay_perftip_count_freecam_enter
syn keyword tf2Command replay_perftip_count_freecam_exit replay_perftip_count_freecam_exit2 replay_playerdeathscreenshotdelay replay_postdeathrecordtime replay_postwinreminderduration
syn keyword tf2Command replay_printclientreplays replay_printqueuedtakes replay_printsessioninfo replay_publish_simulate_delay_ftp replay_publish_simulate_delay_local_http :
syn keyword tf2Command replay_publish_simulate_rename_fail replay_quitmsg_dontaskagain replay_ragdoll_blending replay_ragdoll_dbg replay_ragdoll_tickoffset
syn keyword tf2Command replay_record replay_record_voice replay_recording replay_reloadbrowser replay_removeclientreplay
syn keyword tf2Command replay_renderpause replay_renderqueue_first_add replay_rendersetting_encodingquality replay_rendersetting_exportraw replay_rendersetting_motionblur_can_toggle :
syn keyword tf2Command replay_rendersetting_motionblurenabled replay_rendersetting_motionblurquality replay_rendersetting_quitwhendone replay_rendersetting_renderglow replay_renderunpause
syn keyword tf2Command replay_replayeditor_rewindmsgcounter replay_replaywelcomedlgcount replay_screenshotkilldelay replay_screenshotresolution replay_screenshotsentrykilldelay
syn keyword tf2Command replay_sentrycammaxverticaloffset replay_sentrycamoffset_frontback replay_sentrycamoffset_leftright replay_sentrycamoffset_updown replay_sessioninfo_updatefrequency
syn keyword tf2Command replay_stoprecord replay_test_take_save_dlg replay_voice_during_playback report_entities report_simthinklist
syn keyword tf2Command report_soundpatch report_soundpatch report_touchlinks resetplayerstats respawn_entities
syn keyword tf2Command restart retry rfgc +right -right
syn keyword tf2Command room_type rope_averagelight rope_collide rope_rendersolid rope_shake
syn keyword tf2Command rope_smooth rope_smooth_enlarge rope_smooth_maxalpha rope_smooth_maxalphawidth rope_smooth_minalpha
syn keyword tf2Command rope_smooth_minwidth rope_solid_maxalpha rope_solid_maxwidth rope_solid_minalpha rope_solid_minwidth
syn keyword tf2Command rope_subdiv rope_wind_dist rpt rpt_client_enable rpt_connect
syn keyword tf2Command rpt_download_log rpt_end rpt_password rpt_screenshot rpt_server_enable
syn keyword tf2Command rpt_start rpt_vprof_time rr_debug_qa rr_debugresponses rr_debugrule
syn keyword tf2Command rr_dumpresponses rr_reloadresponsesystems save save_async save_asyncdelay
syn keyword tf2Command save_console save_disable save_finish_async save_history_count save_huddelayframes
syn keyword tf2Command save_in_memory save_noxsave save_replay save_screenshot save_spew
syn keyword tf2Command say say_team sb_close_browser_on_connect sb_dontshow_maxplayer_warning sb_firstopentime
syn keyword tf2Command sb_mod_suggested_maxplayers sb_numtimesopened sb_quick_list_bit_field sb_showblacklists scene_async_prefetch_spew
syn keyword tf2Command scene_clamplookat scene_clientflex scene_flatturn scene_flush scene_forcecombined
syn keyword tf2Command scene_maxcaptionradius scene_print scene_showfaceto scene_showlook scene_showmoveto
syn keyword tf2Command scene_showunlock +score -score scr_centertime screenshot
syn keyword tf2Command sensitivity server_game_time servercfgfile setang setang_exact
syn keyword tf2Command setinfo setmodel setpause setpos setpos_exact
syn keyword tf2Command shake shake_show shake_stop +showbudget -showbudget
syn keyword tf2Command showbudget_texture +showbudget_texture -showbudget_texture +showbudget_texture_global -showbudget_texture_global
syn keyword tf2Command showbudget_texture_global_dumpstats showbudget_texture_global_sum showconsole showhitlocation showinfo
syn keyword tf2Command showmapinfo showpanel showparticlecounts showschemevisualizer +showscores
syn keyword tf2Command -showscores showstatsdlg ShowSteamStatsSessionID showtriggers showtriggers_toggle
syn keyword tf2Command +showvprof -showvprof simple_bot_add singlestep sixense_aim_1to1_heading_multiplier
syn keyword tf2Command sixense_aim_1to1_pitch_multiplier sixense_aim_1to1_ratchet_vertical sixense_aim_freeaim_accel_band_exponent sixense_aim_freeaim_accel_band_size sixense_aim_freeaim_auto_level_rate
syn keyword tf2Command sixense_aim_freeaim_dead_zone_radius sixense_aim_freeaim_heading_multiplier sixense_aim_freeaim_max_speed sixense_aim_freeaim_pitch_multiplier sixense_aim_freeaim_spin_disabled
syn keyword tf2Command sixense_aim_freeaim_switch_blend_time_enter : sixense_aim_freeaim_switch_blend_time_exit : sixense_aim_scope_heading_multiplier sixense_aim_scope_pitch_multiplier sixense_always_draw_crosshair
syn keyword tf2Command sixense_base_offset_x sixense_base_offset_y sixense_base_offset_z sixense_bind sixense_clear_bindings
syn keyword tf2Command sixense_controller_angle_mode sixense_create_default_bindings sixense_crosshair_horiz_multiplier sixense_crosshair_vert_multiplier sixense_crouch_sensitivity
syn keyword tf2Command sixense_delete_binding sixense_disable_gestures sixense_enabled sixense_exit_metroid_blend sixense_exit_one_to_one_dot
syn keyword tf2Command sixense_features_enabled sixense_feet_angles_offset_stick_spin_exponent : sixense_feet_angles_offset_stick_spin_horiz_multiplier : sixense_feet_angles_offset_stick_spin_invert_pitch : sixense_feet_angles_offset_stick_spin_vert_multiplier :
syn keyword tf2Command sixense_filter_level sixense_jump_sensitivity sixense_left_handed +sixense_left_point_gesture -sixense_left_point_gesture
syn keyword tf2Command sixense_list_bindings sixense_max_charge_spin sixense_melee_pitch_blend_val sixense_mode sixense_mouse_enabled
syn keyword tf2Command sixense_mouse_sensitivity sixense_point_gesture_angle_threshold +sixense_ratchet -sixense_ratchet sixense_reload_sensitivity
syn keyword tf2Command +sixense_right_point_gesture -sixense_right_point_gesture sixense_roll_correct_blend sixense_select_grenade sixense_select_machinegun
syn keyword tf2Command sixense_select_melee sixense_select_pistol sixense_sensitivity_level sixense_set_base_offset sixense_set_filter_params
syn keyword tf2Command sixense_show_frame sixense_spring_view_enabled sixense_spring_view_max_angle sixense_spring_view_max_spring sixense_spring_view_min_angle
syn keyword tf2Command sixense_spring_view_min_spring sixense_teleport_metroid_blend_time sixense_teleport_wait_to_blend_time sixense_tilt_gesture_angle_threshold sixense_trigger_threshold
syn keyword tf2Command sixense_walking_dead_zone_percent sixense_walking_exponent sixense_weapon_select_sensitivity sixense_write_bindings sixense_zoom_momentary_time
syn keyword tf2Command sk_ally_regen_time sk_autoaim_mode sk_npc_arm sk_npc_chest sk_npc_head
syn keyword tf2Command sk_npc_leg sk_npc_stomach sk_player_arm sk_player_chest sk_player_head
syn keyword tf2Command sk_player_leg sk_player_stomach sk_plr_dmg_grenade skill skip_next_map
syn keyword tf2Command slot0 slot1 slot10 slot11 slot12
syn keyword tf2Command slot2 slot3 slot4 slot5 slot6
syn keyword tf2Command slot7 slot8 slot9 sm sm_addban
syn keyword tf2Command sm_admin sm_ban sm_banip sm_basepath sm_beacon
syn keyword tf2Command sm_beacon_radius sm_blind sm_burn sm_burn_duration sm_cancelvote
syn keyword tf2Command sm_chat sm_chat_mode sm_conhook_start sm_conhook_stop sm_cookies
syn keyword tf2Command sm_corecfgfile sm_csay sm_cvar sm_datetime_format sm_deadtalk
syn keyword tf2Command sm_drug sm_dump_admcache sm_dump_classes sm_dump_datamaps sm_dump_handles
syn keyword tf2Command sm_dump_netprops sm_dump_netprops_xml sm_dump_teprops sm_execcfg sm_firebomb
syn keyword tf2Command sm_firebomb_mode sm_firebomb_radius sm_firebomb_ticks sm_flood_time sm_freeze
syn keyword tf2Command sm_freeze_duration sm_freezebomb sm_freezebomb_mode sm_freezebomb_radius sm_freezebomb_ticks
syn keyword tf2Command sm_gag sm_gravity sm_help sm_hide_slots sm_hsay
syn keyword tf2Command sm_immunity_mode sm_kick sm_map sm_maphistory sm_menu_sounds
syn keyword tf2Command sm_msay sm_mute sm_nextmap sm_noclip sm_play
syn keyword tf2Command sm_print_telist sm_psay sm_rcon sm_reloadadmins sm_rename
syn keyword tf2Command sm_reserve_kicktype sm_reserve_maxadmins sm_reserve_type sm_reserved_slots sm_resetcvar
syn keyword tf2Command sm_revote sm_say sm_searchcmd sm_settings sm_show_activity
syn keyword tf2Command sm_silence sm_slap sm_slay sm_time_adjustment sm_timebomb
syn keyword tf2Command sm_timebomb_mode sm_timebomb_radius sm_timebomb_ticks sm_timeleft_interval sm_trigger_show
syn keyword tf2Command sm_tsay sm_unban sm_ungag sm_unmute sm_unsilence
syn keyword tf2Command sm_vote sm_vote_alltalk sm_vote_ban sm_vote_burn sm_vote_delay
syn keyword tf2Command sm_vote_ff sm_vote_gravity sm_vote_kick sm_vote_map sm_vote_progress_chat
syn keyword tf2Command sm_vote_progress_client_console sm_vote_progress_console sm_vote_progress_hintbox sm_vote_slay sm_votealltalk
syn keyword tf2Command sm_voteban sm_voteburn sm_voteff sm_votegravity sm_votekick
syn keyword tf2Command sm_votemap sm_voteslay sm_who smoothstairs snapto
syn keyword tf2Command snd_async_flush snd_async_fullyasync snd_async_minsize snd_async_showmem snd_async_spew_blocking
syn keyword tf2Command snd_async_stream_spew snd_cull_duplicates snd_defer_trace snd_delay_sound_shift snd_disable_mixer_duck
syn keyword tf2Command snd_duckerattacktime snd_duckerreleasetime snd_duckerthreshold snd_ducktovolume snd_dumpclientsounds
syn keyword tf2Command snd_foliage_db_loss snd_gain snd_gain_max snd_gain_min snd_legacy_surround
syn keyword tf2Command snd_lockpartial snd_mix_async snd_mixahead snd_musicvolume snd_mute_losefocus
syn keyword tf2Command snd_noextraupdate snd_obscured_gain_dB snd_pitchquality snd_profile snd_rebuildaudiocache
syn keyword tf2Command snd_refdb snd_refdist snd_restart snd_show snd_showclassname
syn keyword tf2Command snd_showmixer snd_showstart snd_ShowThreadFrameTime snd_soundmixer snd_spatialize_roundrobin
syn keyword tf2Command snd_surround_speakers snd_visualize snd_vox_captiontrace snd_vox_globaltimeout snd_vox_sectimetout
syn keyword tf2Command snd_vox_seqtimetout snd_writemanifest sndplaydelay soundfade soundinfo
syn keyword tf2Command soundlist soundpatch_captionlength soundscape_debug soundscape_dumpclient soundscape_fadetime
syn keyword tf2Command soundscape_flush sourcemod_version speak spec_autodirector spec_freeze_distance_max
syn keyword tf2Command spec_freeze_distance_min spec_freeze_time spec_freeze_traveltime spec_mode spec_next
syn keyword tf2Command spec_player spec_pos spec_prev spec_scoreboard spec_track
syn keyword tf2Command +speed -speed spike star_memory startdemos
syn keyword tf2Command startmovie startupmenu stats status steamworks_sessionid_client
syn keyword tf2Command steamworks_sessionid_server step_spline stop stopdemo stopsound
syn keyword tf2Command stopsoundscape store_version +strafe -strafe studio_queue_mode
syn keyword tf2Command stuffcmds suitvolume surfaceprop sv_accelerate sv_airaccelerate
syn keyword tf2Command sv_allow_color_correction sv_allow_voice_from_file sv_allow_votes sv_allow_wait_command sv_allowdownload
syn keyword tf2Command sv_allowupload sv_alltalk sv_alternateticks sv_autosave sv_backspeed
syn keyword tf2Command sv_benchmark_autovprofrecord sv_benchmark_force_start sv_benchmark_freeroam sv_benchmark_numticks sv_bonus_challenge
syn keyword tf2Command sv_bonus_map_challenge_update sv_bonus_map_complete sv_bonus_map_unlock sv_bounce sv_cacheencodedents
syn keyword tf2Command sv_cheats sv_clearhinthistory sv_client_cmdrate_difference sv_client_max_interp_ratio sv_client_min_interp_ratio
syn keyword tf2Command sv_client_predict sv_clockcorrection_msecs sv_consistency sv_contact sv_creationtickcheck
syn keyword tf2Command sv_debug_player_use sv_debug_stuck_particles sv_debugmanualmode sv_debugtempentities sv_deltaprint
syn keyword tf2Command sv_deltatime sv_disable_querycache sv_downloadurl sv_dumpstringtables sv_enableoldqueries
syn keyword tf2Command sv_filterban sv_findsoundname sv_footsteps sv_force_transmit_ents sv_forcepreload
syn keyword tf2Command sv_friction sv_gravity sv_hudhint_sound sv_ignore_hitboxes sv_instancebaselines
syn keyword tf2Command sv_lagcompensation_teleport_dist sv_lagflushbonecache sv_lan sv_log_onefile sv_logbans
syn keyword tf2Command sv_logblocks sv_logdownloadlist sv_logecho sv_logfile sv_logflush
syn keyword tf2Command sv_logsdir sv_logsecret sv_lowedict_action sv_lowedict_threshold sv_massreport
syn keyword tf2Command sv_master_share_game_socket sv_max_connects_sec sv_max_connects_sec_global sv_max_connects_window sv_max_queries_sec
syn keyword tf2Command sv_max_queries_sec_global sv_max_queries_window sv_max_usercmd_future_ticks sv_maxcmdrate sv_maxrate
syn keyword tf2Command sv_maxreplay sv_maxroutable sv_maxspeed sv_maxunlag sv_maxupdaterate
syn keyword tf2Command sv_maxvelocity sv_memlimit sv_mincmdrate sv_minrate sv_minupdaterate
syn keyword tf2Command sv_namechange_cooldown_seconds sv_netspike_on_reliable_snapshot_overflow : sv_netvisdist sv_noclipaccelerate sv_noclipduringpause
syn keyword tf2Command sv_noclipspeed sv_npc_talker_maxdist sv_optimizedmovement sv_parallel_packentities sv_parallel_sendsnapshot
syn keyword tf2Command sv_password sv_pausable sv_playerperfhistorycount sv_precacheinfo sv_proj_stunball_damage
syn keyword tf2Command sv_pure sv_pure_kick_clients sv_pure_trace sv_pushaway_clientside sv_pushaway_clientside_size
syn keyword tf2Command sv_pushaway_force sv_pushaway_max_force sv_pushaway_max_player_force sv_pushaway_min_player_speed sv_pushaway_player_force
syn keyword tf2Command sv_pvsskipanimation sv_querycache_stats sv_rcon_banpenalty sv_rcon_log sv_rcon_maxfailures
syn keyword tf2Command sv_rcon_maxpacketbans sv_rcon_maxpacketsize sv_rcon_minfailures sv_rcon_minfailuretime sv_region
syn keyword tf2Command sv_registration_message sv_registration_successful sv_restrict_aspect_ratio_fov sv_rollangle sv_rollspeed
syn keyword tf2Command sv_runcmds sv_sendtables sv_showanimstate sv_showanimstate_log sv_showladders
syn keyword tf2Command sv_showlagcompensation sv_shutdown sv_skyname sv_soundemitter_filecheck sv_soundemitter_flush
syn keyword tf2Command sv_soundemitter_trace sv_soundscape_printdebuginfo sv_specaccelerate sv_specnoclip sv_specspeed
syn keyword tf2Command sv_stats sv_steamblockingcheck sv_steamgroup sv_stepsize sv_stickysprint_default
syn keyword tf2Command sv_stopspeed sv_stressbots sv_strict_notarget sv_suppress_viewpunch sv_tags
syn keyword tf2Command sv_test_scripted_sequences sv_teststepsimulation sv_thinktimecheck sv_timeout sv_turbophysics
syn keyword tf2Command sv_unlag sv_unlag_debug sv_unlag_fixstuck sv_unlockedchapters sv_use_steam_voice
syn keyword tf2Command sv_useexplicitdelete sv_vehicle_autoaim_scale sv_visiblemaxplayers sv_voicecodec sv_voiceenable
syn keyword tf2Command sv_vote_allow_spectators sv_vote_command_delay sv_vote_creation_timer sv_vote_failure_timer sv_vote_failure_timer_mvm
syn keyword tf2Command sv_vote_issue_changelevel_allowed sv_vote_issue_changelevel_allowed_mvm sv_vote_issue_kick_allowed sv_vote_issue_kick_allowed_mvm sv_vote_issue_kick_spectators_mvm
syn keyword tf2Command sv_vote_issue_mvm_challenge_allowed sv_vote_issue_nextlevel_allowed sv_vote_issue_nextlevel_allowextend sv_vote_issue_nextlevel_choicesmode sv_vote_issue_nextlevel_prevent_change
syn keyword tf2Command sv_vote_issue_restart_game_allowed sv_vote_issue_scramble_teams_allowed sv_vote_kick_ban_duration sv_vote_timer_duration sv_vote_ui_hide_disabled_issues
syn keyword tf2Command sv_wateraccelerate sv_waterdist sv_waterfriction sys_minidumpexpandedspew sys_minidumpspewlines
syn keyword tf2Command systemlinkport template_debug Test_CreateEntity test_dispatcheffect Test_EHandle
syn keyword tf2Command test_entity_blocker test_freezeframe test_giveawayitem Test_InitRandomEntitySpawner Test_ProxyToggle_EnableProxy
syn keyword tf2Command Test_ProxyToggle_EnsureValue Test_ProxyToggle_SetValue Test_RandomizeInPVS Test_RandomPlayerPosition Test_RemoveAllRandomEntities
syn keyword tf2Command Test_SpawnRandomEntities testhudanim testscript_debug teststatpanel texture_budget_background_alpha
syn keyword tf2Command texture_budget_panel_bottom_of_history_fraction : texture_budget_panel_global texture_budget_panel_height texture_budget_panel_width texture_budget_panel_x
syn keyword tf2Command texture_budget_panel_y tf_allow_player_use tf_allow_taunt_switch tf_always_deathanim tf_always_loser
syn keyword tf2Command tf_archer_proxy_fire_rate tf_arena_change_limit tf_arena_first_blood tf_arena_force_class tf_arena_max_streak
syn keyword tf2Command tf_arena_override_cap_enable_time tf_arena_override_team_size tf_arena_preround_time tf_arena_round_time tf_arena_use_queue
syn keyword tf2Command tf_avoidteammates tf_avoidteammates_pushaway tf_backstab_detection_method tf_base_boss_max_turn_rate tf_base_boss_speed
syn keyword tf2Command tf_birthday tf_birthday_ball_chance tf_boost_drain_time tf_bot_add tf_bot_always_full_reload
syn keyword tf2Command tf_bot_ammo_search_range tf_bot_arrow_elevation_rate tf_bot_auto_vacate tf_bot_ballistic_elevation_rate tf_bot_capture_seek_and_destroy_max_duration :
syn keyword tf2Command tf_bot_capture_seek_and_destroy_min_duration : tf_bot_cart_push_radius tf_bot_choose_target_interval tf_bot_count tf_bot_debug_ammo_scavenging
syn keyword tf2Command tf_bot_debug_destroy_enemy_sentry tf_bot_debug_payload_guard_vantage_points : tf_bot_debug_retreat_to_cover tf_bot_debug_seek_and_destroy tf_bot_debug_sentry_placement
syn keyword tf2Command tf_bot_debug_sniper tf_bot_debug_spy tf_bot_debug_stuck_log tf_bot_defend_owned_point_percent tf_bot_defense_debug
syn keyword tf2Command tf_bot_defense_must_defend_time tf_bot_difficulty tf_bot_engineer_exit_near_sentry_range tf_bot_engineer_max_sentry_travel_distance_to_point : tf_bot_engineer_retaliate_range
syn keyword tf2Command tf_bot_escort_range tf_bot_fetch_lost_flag_time tf_bot_fire_weapon_allowed tf_bot_fire_weapon_min_time tf_bot_flag_escort_give_up_range
syn keyword tf2Command tf_bot_flag_escort_max_count tf_bot_flag_escort_range tf_bot_flag_kill_on_touch tf_bot_force_class tf_bot_force_jump
syn keyword tf2Command tf_bot_formation_debug tf_bot_health_critical_ratio tf_bot_health_ok_ratio tf_bot_health_search_far_range tf_bot_health_search_near_range
syn keyword tf2Command tf_bot_hitscan_range_limit tf_bot_join_after_player tf_bot_keep_class_after_death tf_bot_kick tf_bot_kill
syn keyword tf2Command tf_bot_max_grenade_launch_at_sentry_range : tf_bot_max_point_defend_range tf_bot_max_setup_gate_defend_range tf_bot_max_sticky_launch_at_sentry_range : tf_bot_max_teleport_entrance_travel
syn keyword tf2Command tf_bot_max_teleport_exit_travel_to_point : tf_bot_medic_cover_test_resolution tf_bot_medic_debug tf_bot_medic_max_call_response_range tf_bot_medic_max_heal_range
syn keyword tf2Command tf_bot_medic_start_follow_range tf_bot_medic_stop_follow_range tf_bot_melee_attack_abandon_range tf_bot_melee_only tf_bot_min_setup_gate_defend_range
syn keyword tf2Command tf_bot_min_setup_gate_sniper_defend_range : tf_bot_min_teleport_travel tf_bot_near_point_travel_distance tf_bot_notice_backstab_chance tf_bot_notice_backstab_max_range
syn keyword tf2Command tf_bot_notice_backstab_min_range tf_bot_notice_gunfire_range tf_bot_notice_quiet_gunfire_range tf_bot_npc_archer_arrow_damage tf_bot_npc_archer_health
syn keyword tf2Command tf_bot_npc_archer_shoot_interval tf_bot_npc_archer_speed tf_bot_offense_must_push_time tf_bot_offline_practice tf_bot_path_lookahead_range
syn keyword tf2Command tf_bot_payload_guard_range tf_bot_prefix_name_with_difficulty tf_bot_pyro_always_reflect tf_bot_pyro_deflect_tolerance tf_bot_pyro_shove_away_range
syn keyword tf2Command tf_bot_quota tf_bot_quota_mode tf_bot_retreat_to_cover_range tf_bot_sniper_aim_error tf_bot_sniper_aim_steady_rate
syn keyword tf2Command tf_bot_sniper_allow_opportunistic tf_bot_sniper_choose_target_interval tf_bot_sniper_flee_range tf_bot_sniper_goal_entity_move_tolerance : tf_bot_sniper_linger_time
syn keyword tf2Command tf_bot_sniper_melee_range tf_bot_sniper_patience_duration tf_bot_sniper_personal_space_range tf_bot_sniper_spot_epsilon tf_bot_sniper_spot_max_count
syn keyword tf2Command tf_bot_sniper_spot_min_range tf_bot_sniper_spot_point_tolerance tf_bot_sniper_spot_search_count tf_bot_sniper_target_linger_duration tf_bot_spy_change_target_range_threshold :
syn keyword tf2Command tf_bot_spy_knife_range tf_bot_squad_escort_range tf_bot_sticky_base_range tf_bot_sticky_charge_rate tf_bot_stickybomb_density
syn keyword tf2Command tf_bot_suicide_bomb_range tf_bot_taunt_victim_chance tf_bot_teleport_build_surface_normal_limit : tf_bot_wait_in_cover_max_time tf_bot_wait_in_cover_min_time
syn keyword tf2Command tf_bot_warp_team_to_me tf_build_menu_controller_mode tf_caplinear tf_chargedfriends tf_cheapobjects
syn keyword tf2Command tf_clamp_airducks tf_clamp_back_speed tf_clamp_back_speed_min tf_clear_attribute tf_clientsideeye_lookats
syn keyword tf2Command tf_coach_min_time_played tf_coach_request_nevershowagain tf_colorblindassist tf_crashclient tf_ctf_bonus_time
syn keyword tf2Command tf_damage_disablespread tf_damage_events_track_for tf_damage_lineardist tf_damage_multiplier_blue tf_damage_multiplier_red
syn keyword tf2Command tf_damage_range tf_damageforcescale_other tf_damageforcescale_self_soldier_badrj tf_damageforcescale_self_soldier_rj tf_damagescale_self_soldier
syn keyword tf2Command tf_debug_ballistic_targeting tf_debug_ballistic_targeting_tolerance tf_debug_ballistics tf_debug_ballistics_init_vel_scale tf_debug_ballistics_max_time
syn keyword tf2Command tf_debug_ballistics_timestep tf_debug_damage tf_debug_flamethrower tf_debug_placement_failure tf_debugsentrydamage
syn keyword tf2Command tf_decoy_lifetime tf_demoman_charge_drain_time tf_demoman_charge_regen_rate tf_deploying_bomb_delay_time tf_deploying_bomb_time
syn keyword tf2Command tf_dev_health_on_damage_recover_percentage : tf_dev_marked_for_death_lifetime tf_dingaling_pitchmaxdmg tf_dingaling_pitchmindmg tf_dingaling_volume
syn keyword tf2Command tf_dingalingaling tf_dingalingaling_repeat_delay tf_disguise_menu_controller_mode tf_dumpplayerstats tf_escort_recede_time
syn keyword tf2Command tf_escort_recede_time_overtime tf_escort_score_rate tf_explanations_backpackpanel tf_explanations_charinfo_armory_panel tf_explanations_charinfopanel
syn keyword tf2Command tf_explanations_craftingpanel tf_explanations_discardpanel tf_explanations_store tf_explanations_tradingpanel tf_eyeball_boss_acceleration
syn keyword tf2Command tf_eyeball_boss_attack_range tf_eyeball_boss_debug tf_eyeball_boss_debug_orientation tf_eyeball_boss_health_at_level_2 tf_eyeball_boss_health_base
syn keyword tf2Command tf_eyeball_boss_health_per_level tf_eyeball_boss_health_per_player tf_eyeball_boss_horiz_damping tf_eyeball_boss_hover_height tf_eyeball_boss_lifetime
syn keyword tf2Command tf_eyeball_boss_speed tf_eyeball_boss_vert_damping tf_fastbuild tf_feign_death_damage_scale tf_feign_death_duration
syn keyword tf2Command tf_flag_caps_per_round tf_flamethrower_boxsize tf_flamethrower_burst_zvelocity tf_flamethrower_burstammo tf_flamethrower_drag
syn keyword tf2Command tf_flamethrower_flametime tf_flamethrower_float tf_flamethrower_maxdamagedist tf_flamethrower_shortrangedamagemultiplier : tf_flamethrower_vecrand
syn keyword tf2Command tf_flamethrower_velocity tf_flamethrower_velocityfadeend tf_flamethrower_velocityfadestart tf_force_holidays_off tf_forced_holiday
syn keyword tf2Command tf_gamemode_arena tf_gamemode_cp tf_gamemode_ctf tf_gamemode_mvm tf_gamemode_payload
syn keyword tf2Command tf_gamemode_sd tf_grenade_force_sleeptime tf_grenade_forcefrom_blast tf_grenade_forcefrom_buckshot tf_grenade_forcefrom_bullet
syn keyword tf2Command tf_grenade_show_radius tf_grenade_show_radius_time tf_grenadelauncher_chargescale tf_grenadelauncher_livetime tf_grenadelauncher_min_contact_speed
syn keyword tf2Command tf_halloween_boss_spawn_interval tf_halloween_boss_spawn_interval_variation : tf_halloween_bot_attack_range tf_halloween_bot_chase_duration tf_halloween_bot_chase_range
syn keyword tf2Command tf_halloween_bot_health_base tf_halloween_bot_health_per_player tf_halloween_bot_min_player_count tf_halloween_bot_quit_range tf_halloween_bot_speed
syn keyword tf2Command tf_halloween_bot_speed_recovery_rate tf_halloween_bot_terrify_radius tf_halloween_eyeball_boss_spawn_interval : tf_halloween_eyeball_boss_spawn_interval_variation : tf_halloween_force_boss_spawn
syn keyword tf2Command tf_highfive_close_range tf_highfive_debug tf_highfive_height_tolerance tf_highfive_hintcount tf_highfive_max_range
syn keyword tf2Command tf_highfive_separation tf_hud_no_crosshair_on_scope_zoom tf_hud_notification_duration tf_hud_num_building_alert_beeps tf_ignite_player
syn keyword tf2Command tf_impactwatertime tf_impactwatertimeenable tf_invite_debug tf_invuln_time tf_last_store_pricesheet_version
syn keyword tf2Command tf_lobby_debug tf_mark tf_matchgroups tf_matchmaking_goodenough_count_end tf_matchmaking_goodenough_count_start
syn keyword tf2Command tf_matchmaking_goodenough_score_end tf_matchmaking_goodenough_score_start tf_matchmaking_join_in_progress tf_matchmaking_max_search_time tf_matchmaking_noob_hours_played
syn keyword tf2Command tf_matchmaking_noob_map_score_boost tf_matchmaking_numbers_increase_maxplayers_penalty : tf_matchmaking_numbers_serverfull_headroom : tf_matchmaking_numbers_valve_bonus_hrs_a : tf_matchmaking_numbers_valve_bonus_hrs_b :
syn keyword tf2Command tf_matchmaking_numbers_valve_bonus_pts_a : tf_matchmaking_numbers_valve_bonus_pts_b : tf_matchmaking_ogs_odds tf_matchmaking_ping_a tf_matchmaking_ping_a_score
syn keyword tf2Command tf_matchmaking_ping_b tf_matchmaking_ping_b_score tf_matchmaking_ping_c tf_matchmaking_ping_c_score tf_matchmaking_retry_cooldown_seconds
syn keyword tf2Command tf_matchmaking_retry_max_penalty tf_matchmaking_spew_level tf_matchmaking_ticket_help tf_max_charge_speed tf_max_health_boost
syn keyword tf2Command tf_max_separation_force tf_max_voice_speak_delay tf_maxspeed tf_medieval tf_medieval_autorp
syn keyword tf2Command tf_medieval_cam_idealdist tf_medieval_cam_idealdistright tf_medieval_cam_idealdistup tf_medieval_cam_idealpitch tf_medieval_thirdperson
syn keyword tf2Command tf_medigun_autoheal tf_medigun_lagcomp tf_meleeattackforcescale tf_mm_mannup_disabled tf_mm_player_reservation_timeout_seconds :
syn keyword tf2Command tf_mm_servermode tf_mm_strict tf_mm_trusted tf_mvm_bot_allow_flag_carrier_to_fight tf_mvm_bot_flag_carrier_health_regen
syn keyword tf2Command tf_mvm_bot_flag_carrier_interval_to_1st_upgrade : tf_mvm_bot_flag_carrier_interval_to_2nd_upgrade : tf_mvm_bot_flag_carrier_interval_to_3rd_upgrade : tf_mvm_bot_flag_carrier_movement_penalty : tf_mvm_bot_sniper_target_by_dps
syn keyword tf2Command tf_mvm_checkpoint tf_mvm_checkpoint_clear tf_mvm_classupgradehelpcount tf_mvm_death_penalty tf_mvm_default_sentry_buster_damage_dealt_threshold :
syn keyword tf2Command tf_mvm_default_sentry_buster_kill_threshold : tf_mvm_disconnect_on_victory tf_mvm_force_victory tf_mvm_jump_to_wave tf_mvm_min_players_to_start
syn keyword tf2Command tf_mvm_miniboss_scale tf_mvm_missioncyclefile tf_mvm_notice_sapped_squadmates_delay tf_mvm_popfile tf_mvm_skill
syn keyword tf2Command tf_mvm_tabs_discovered tf_mvm_tank_health tf_mvm_tank_kill tf_nav_combat_build_rate tf_nav_combat_decay_rate
syn keyword tf2Command tf_nav_in_combat_duration tf_nav_in_combat_range tf_nav_show_incursion_distance tf_nav_show_turf_ownership tf_obj_build_rotation_speed
syn keyword tf2Command tf_obj_damage_tank_achievement_amount tf_obj_gib_maxspeed tf_obj_gib_velocity_max tf_obj_gib_velocity_min tf_obj_ground_clearance
syn keyword tf2Command tf_obj_max_attach_dist tf_obj_upgrade_per_hit tf_overtime_nag tf_particles_disable_weather tf_party_debug
syn keyword tf2Command tf_pipebomb_deflect_reset_time tf_pipebomb_force_to_move tf_player_movement_stun_time tf_playergib tf_playergib_maxspeed
syn keyword tf2Command tf_playersgib_force tf_playersgib_forceup tf_playerstatetransitions tf_populator_active_buffer_range tf_populator_damage_multiplier
syn keyword tf2Command tf_populator_debug tf_populator_health_multiplier tf_pressandhold_minduration tf_quickplay_beta_ask_percentage tf_quickplay_beta_preference
syn keyword tf2Command tf_quickplay_lastviewedmode tf_raid_engineer_infinte_metal tf_recent_achievements tf_remember_activeweapon tf_remember_lastswitched
syn keyword tf2Command tf_replay_pyrovision tf_resolve_stuck_players tf_respawn_on_loadoutchanges tf_roundinfo_pause tf_scout_air_dash_count
syn keyword tf2Command tf_scout_bat_launch_delay tf_scout_energydrink_activation tf_scout_energydrink_consume_rate tf_scout_energydrink_regen_rate tf_scout_hype_mod
syn keyword tf2Command tf_scout_hype_pep_max tf_scout_hype_pep_min_damage tf_scout_hype_pep_mod tf_scout_stunball_base_duration tf_scout_stunball_base_speed
syn keyword tf2Command tf_select_ambush_areas tf_select_ambush_areas_close_range tf_select_ambush_areas_max_enemy_exposure_area : tf_select_ambush_areas_radius tf_select_with_attribute
syn keyword tf2Command tf_sentrygun_ammocheat tf_sentrygun_damage tf_sentrygun_kill_after_redeploy_time_achievement : tf_sentrygun_max_absorbed_damage_while_controlled_for_achievement : tf_sentrygun_metal_per_rocket
syn keyword tf2Command tf_sentrygun_metal_per_shell tf_sentrygun_mini_damage tf_sentrygun_newtarget_dist tf_sentrygun_notarget tf_server_identity_account_id
syn keyword tf2Command tf_server_identity_disable_quickplay tf_server_identity_token tf_server_lobby_debug tf_show_actor_potential_visibility tf_show_blocked_areas
syn keyword tf2Command tf_show_bomb_drop_areas tf_show_control_points tf_show_enemy_invasion_areas tf_show_gate_defense_areas tf_show_in_combat_areas
syn keyword tf2Command tf_show_incursion_flow tf_show_incursion_flow_gradient tf_show_incursion_flow_range tf_show_incursion_range tf_show_incursion_range_max
syn keyword tf2Command tf_show_incursion_range_min tf_show_mesh_decoration tf_show_mesh_decoration_manual tf_show_point_defense_areas tf_show_preset_explanation_in_class_loadout :
syn keyword tf2Command tf_show_sentry_danger tf_show_sniper_areas tf_show_sniper_areas_safety_range tf_show_train_path tf_showspeed
syn keyword tf2Command tf_simple_disguise_menu tf_sniper_fullcharge_bell tf_soldier_buff_pulses tf_solidobjects tf_spectate_pyrovision
syn keyword tf2Command tf_spectator_target_location tf_spy_cloak_consume_rate tf_spy_cloak_no_attack_time tf_spy_cloak_regen_rate tf_spy_invis_time
syn keyword tf2Command tf_spy_invis_unstealth_time tf_spy_max_cloaked_speed tf_stalematechangeclasstime tf_stats_nogameplaycheck tf_stats_track
syn keyword tf2Command tf_steam_workshop_query_timeout tf_tauntcam_dist tf_tauntcam_pitch tf_tauntcam_speed tf_tauntcam_yaw
syn keyword tf2Command tf_teammate_max_invis tf_teamtalk tf_teleporter_fov_start tf_teleporter_fov_time tf_test_hat_bodygroup
syn keyword tf2Command tf_test_teleport_home_fx tf_testitem_recent tf_testrr tf_testvcd tf_tournament_classlimit_demoman
syn keyword tf2Command tf_tournament_classlimit_engineer tf_tournament_classlimit_heavy tf_tournament_classlimit_medic tf_tournament_classlimit_pyro tf_tournament_classlimit_scout
syn keyword tf2Command tf_tournament_classlimit_sniper tf_tournament_classlimit_soldier tf_tournament_classlimit_spy tf_tournament_hide_domination_icons tf_training_client_message
syn keyword tf2Command tf_training_has_prompted_for_forums tf_training_has_prompted_for_loadout tf_training_has_prompted_for_offline_practice : tf_training_has_prompted_for_options tf_training_has_prompted_for_training
syn keyword tf2Command tf_use_fixed_weaponspreads tf_useparticletracers tf_weapon_criticals tf_weapon_ragdoll_maxspeed tf_weapon_ragdoll_velocity_max
syn keyword tf2Command tf_weapon_ragdoll_velocity_min tf_weapon_select_demo_start_delay tf_weapon_select_demo_time tf_whip_speed_increase tf_wipe_attributes
syn keyword tf2Command think_limit thirdperson thirdperson_mayamode thirdperson_platformer thirdperson_screenspace
syn keyword tf2Command threadpool_affinity timedemo timedemoquit timeleft timerefresh
syn keyword tf2Command toggle toggle_duck toggleconsole togglescores trace_report
syn keyword tf2Command tracer_extra TrackerAnim training_can_build_dispenser training_can_build_sentry training_can_build_tele_entrance
syn keyword tf2Command training_can_build_tele_exit training_can_destroy_buildings training_can_pickup_dispenser training_can_pickup_sentry training_can_pickup_tele_entrance
syn keyword tf2Command training_can_pickup_tele_exit training_can_select_weapon_building training_can_select_weapon_item1 training_can_select_weapon_item2 training_can_select_weapon_melee
syn keyword tf2Command training_can_select_weapon_pda training_can_select_weapon_primary training_can_select_weapon_secondary training_class training_continue
syn keyword tf2Command training_map_video training_showdlg tv_allow_camera_man tv_allow_static_shots tv_autorecord
syn keyword tf2Command tv_autoretry tv_chatgroupsize tv_chattimelimit tv_clients tv_debug
syn keyword tf2Command tv_delay tv_delaymapchange tv_deltacache tv_dispatchmode tv_enable
syn keyword tf2Command tv_maxclients tv_maxrate tv_msg tv_name tv_nochat
syn keyword tf2Command tv_overridemaster tv_password tv_port tv_record tv_relay
syn keyword tf2Command tv_relaypassword tv_relayvoice tv_retry tv_snapshotrate tv_status
syn keyword tf2Command tv_stop tv_stoprecord tv_timeout tv_title tv_transmitall
syn keyword tf2Command ui_posedebug_fade_in_time ui_posedebug_fade_out_time unbind unbind_mac unbindall
syn keyword tf2Command unpause use +use -use +use_action_slot_item
syn keyword tf2Command -use_action_slot_item user user_context user_context user_property
syn keyword tf2Command user_property users v_centermove v_centerspeed vcollide_wireframe
syn keyword tf2Command vcr_verbose vehicle_flushscript version vgui_drawfocus vgui_drawtree
syn keyword tf2Command +vgui_drawtree -vgui_drawtree vgui_drawtree_bounds vgui_drawtree_clear vgui_drawtree_draw_selected
syn keyword tf2Command vgui_drawtree_freeze vgui_drawtree_hidden vgui_drawtree_panelalpha vgui_drawtree_panelptr vgui_drawtree_popupsonly
syn keyword tf2Command vgui_drawtree_render_order vgui_drawtree_visible vgui_message_dialog_modal vgui_togglepanel video_quicktime_decode_gamma
syn keyword tf2Command video_quicktime_encode_gamma viewanim_addkeyframe viewanim_create viewanim_load viewanim_reset
syn keyword tf2Command viewanim_save viewanim_test viewmodel_fov viewmodel_fov_demo violence_ablood
syn keyword tf2Command violence_agibs violence_hblood violence_hgibs voice_avggain voice_clientdebug
syn keyword tf2Command voice_debugfeedback voice_debugfeedbackfrom voice_enable voice_fadeouttime voice_forcemicrecord
syn keyword tf2Command voice_inputfromfile voice_loopback voice_maxgain voice_menu_1 voice_menu_2
syn keyword tf2Command voice_menu_3 voice_modenable voice_overdrive voice_overdrivefadetime voice_printtalkers
syn keyword tf2Command voice_profile voice_recordtofile voice_scale voice_serverdebug voice_showchannels
syn keyword tf2Command voice_showincoming voice_steal voice_writevoices +voicerecord -voicerecord
syn keyword tf2Command volume vortex_book_offset vortex_fade_fraction_denom vortex_float_amp vortex_float_osc_speed
syn keyword tf2Command vox_reload voxeltree_box voxeltree_playerview voxeltree_sphere voxeltree_view
syn keyword tf2Command vprof vprof_adddebuggroup1 vprof_cachemiss vprof_cachemiss_off vprof_cachemiss_on
syn keyword tf2Command vprof_child vprof_collapse_all vprof_counters vprof_dump_groupnames vprof_dump_oninterval
syn keyword tf2Command vprof_dump_spikes vprof_dump_spikes_budget_group vprof_dump_spikes_node vprof_expand_all vprof_expand_group
syn keyword tf2Command vprof_generate_report vprof_generate_report_AI vprof_generate_report_AI_only vprof_generate_report_budget vprof_generate_report_hierarchy
syn keyword tf2Command vprof_generate_report_map_load vprof_graph vprof_graphheight vprof_graphwidth vprof_nextsibling
syn keyword tf2Command vprof_off vprof_on vprof_parent vprof_playback_average vprof_playback_start
syn keyword tf2Command vprof_playback_step vprof_playback_stepback vprof_playback_stop vprof_prevsibling vprof_record_start
syn keyword tf2Command vprof_record_stop vprof_remote_start vprof_remote_stop vprof_reset vprof_reset_peaks
syn keyword tf2Command vprof_scope vprof_scope_entity_gamephys vprof_scope_entity_thinks vprof_unaccounted_limit vprof_verbose
syn keyword tf2Command vprof_vtune_group vprof_warningmsec vtune +walk -walk
syn keyword tf2Command wc_air_edit_further wc_air_edit_nearer wc_air_node_edit wc_create wc_destroy
syn keyword tf2Command wc_destroy_undo wc_link_edit weapon_medigun_charge_rate weapon_medigun_chargerelease_rate weapon_medigun_construction_rate
syn keyword tf2Command weapon_medigun_damage_modifier weapon_showproficiency windows_speaker_config wipe_nav_attributes writeid
syn keyword tf2Command writeip x360_audio_english x360_resolution_height x360_resolution_interlaced x360_resolution_widescreen_mode
syn keyword tf2Command x360_resolution_width xbox_autothrottle xbox_steering_deadzone xbox_throttlebias xbox_throttlespoof
syn keyword tf2Command xc_crouch_debounce xload xlook xmove xsave
syn keyword tf2Command youtube_http_proxy youtube_username +zoom -zoom zoom_sensitivity_ratio
 }}}

" {{{ Highlighting
hi def link tf2Todo Todo
hi def link tf2Comment Comment

hi def link tf2Number Constant
hi def link tf2Float Constant
hi def link tf2Command Keyword
hi def link tf2Identifier Identifier
hi def link tf2Type Type
hi def link tf2Key Function
" }}}

let b:current_syntax="tf2"

